require:
  - rubocop-rails
  - rubocop-graphql
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0.2
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
    - 'app/views/**/*'
    - 'config/**/*'
    - 'bin/*'
    - 'Rakefile'
    - 'vendor/**/*'
    - 'tmp/**/*'

Bundler/OrderedGems:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: indent

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Layout/LineLength:
  AllowURI: true
  Enabled: false

GraphQL/ExtractInputType:
  Include:
    - 'graphql/mutations/**/*.rb'
