production: &base
  pagination:
    limit: 25

  # Built in monitoring settings
  monitoring:
    # IP whitelist to access monitoring endpoints
    ip_whitelist:
      - 127.0.0.0/8

  rack_attack:
    # Rack Attack IP banning enabled
    enabled: true
    #
    # Whitelist requests from 127.0.0.1 for web proxies (NGINX/Apache) with incorrect headers
    ip_whitelist:
      - 127.0.0.1
    #
    # Limit the number of Git HTTP authentication attempts per IP
    maxretry: 10
    #
    # Reset the auth attempt counter per IP after 60 seconds
    findtime: 60
    #
    # Ban an IP for one hour (3600s) after too many auth attempts
    bantime: 3600

  booky:
    ## Web server settings (note: host is the FQDN, do not include http://)
    host: localhost
    port: 80 # Set to 443 if using HTTPS, see installation.md#using-https for additional HTTPS configuration details
    https: false # Set to true if using HTTPS, see installation.md#using-https for additional HTTPS configuration details

  ## Uploads (attachments, avatars, etc...)
  uploads:
    # The location where uploads objects are stored (default: public/).
    # storage_path: public/
    # base_dir: uploads/-/system
    object_store:
      enabled: false
      remote_directory: uploads # Bucket name
      # direct_upload: false # Use Object Storage directly for uploads instead of background uploads if enabled (Default: false)
      # background_upload: false # Temporary option to limit automatic upload (Default: true)
      # proxy_download: false # Passthrough all downloads via GitLab instead of using Redirects to Object Storage
      connection:
        provider: AWS
        aws_access_key_id: AWS_ACCESS_KEY_ID
        aws_secret_access_key: AWS_SECRET_ACCESS_KEY
        aws_signature_version: 4 # For creation of signed URLs. Set to 2 if provider does not support v4.
        region: us-east-1
        # host: 'localhost' # default: s3.amazonaws.com
        # endpoint: 'http://127.0.0.1:9000' # default: nil
        # path_style: true # Use 'host/bucket_name/object' instead of 'bucket_name.host/object'
  gravatar:

development:
  <<: *base

test:
  <<: *base

staging:
  <<: *base
